//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <iostream>
#include <vector>
#include "internal/Absyn.H"

/********************   BoolExpAnd    ********************/
BoolExpAnd::BoolExpAnd(BoolExp *p1, BoolExp *p2)
{
  boolexp_1 = p1;
  boolexp_2 = p2;

}

BoolExpAnd::BoolExpAnd(const BoolExpAnd & other)
{
  boolexp_1 = other.boolexp_1->clone();
  boolexp_2 = other.boolexp_2->clone();

}

BoolExpAnd &BoolExpAnd::operator=(const BoolExpAnd & other)
{
  BoolExpAnd tmp(other);
  swap(tmp);
  return *this;
}

void BoolExpAnd::swap(BoolExpAnd & other)
{
  std::swap(boolexp_1, other.boolexp_1);
  std::swap(boolexp_2, other.boolexp_2);

}

BoolExpAnd::~BoolExpAnd()
{
  delete(boolexp_1);
  delete(boolexp_2);

}

void BoolExpAnd::accept(Visitor *v)
{
  v->visitBoolExpAnd(this);
}

BoolExpAnd *BoolExpAnd::clone() const
{
  return new BoolExpAnd(*this);
}



/********************   BoolExpOr    ********************/
BoolExpOr::BoolExpOr(BoolExp *p1, BoolExp *p2)
{
  boolexp_1 = p1;
  boolexp_2 = p2;

}

BoolExpOr::BoolExpOr(const BoolExpOr & other)
{
  boolexp_1 = other.boolexp_1->clone();
  boolexp_2 = other.boolexp_2->clone();

}

BoolExpOr &BoolExpOr::operator=(const BoolExpOr & other)
{
  BoolExpOr tmp(other);
  swap(tmp);
  return *this;
}

void BoolExpOr::swap(BoolExpOr & other)
{
  std::swap(boolexp_1, other.boolexp_1);
  std::swap(boolexp_2, other.boolexp_2);

}

BoolExpOr::~BoolExpOr()
{
  delete(boolexp_1);
  delete(boolexp_2);

}

void BoolExpOr::accept(Visitor *v)
{
  v->visitBoolExpOr(this);
}

BoolExpOr *BoolExpOr::clone() const
{
  return new BoolExpOr(*this);
}



/********************   BoolExpNot    ********************/
BoolExpNot::BoolExpNot(BoolExp *p1)
{
  boolexp_ = p1;

}

BoolExpNot::BoolExpNot(const BoolExpNot & other)
{
  boolexp_ = other.boolexp_->clone();

}

BoolExpNot &BoolExpNot::operator=(const BoolExpNot & other)
{
  BoolExpNot tmp(other);
  swap(tmp);
  return *this;
}

void BoolExpNot::swap(BoolExpNot & other)
{
  std::swap(boolexp_, other.boolexp_);

}

BoolExpNot::~BoolExpNot()
{
  delete(boolexp_);

}

void BoolExpNot::accept(Visitor *v)
{
  v->visitBoolExpNot(this);
}

BoolExpNot *BoolExpNot::clone() const
{
  return new BoolExpNot(*this);
}



/********************   BoolCompExp    ********************/
BoolCompExp::BoolCompExp(CompExp *p1)
{
  compexp_ = p1;

}

BoolCompExp::BoolCompExp(const BoolCompExp & other)
{
  compexp_ = other.compexp_->clone();

}

BoolCompExp &BoolCompExp::operator=(const BoolCompExp & other)
{
  BoolCompExp tmp(other);
  swap(tmp);
  return *this;
}

void BoolCompExp::swap(BoolCompExp & other)
{
  std::swap(compexp_, other.compexp_);

}

BoolCompExp::~BoolCompExp()
{
  delete(compexp_);

}

void BoolCompExp::accept(Visitor *v)
{
  v->visitBoolCompExp(this);
}

BoolCompExp *BoolCompExp::clone() const
{
  return new BoolCompExp(*this);
}



/********************   BoolStrExp    ********************/
BoolStrExp::BoolStrExp(StrExp *p1)
{
  strexp_ = p1;

}

BoolStrExp::BoolStrExp(const BoolStrExp & other)
{
  strexp_ = other.strexp_->clone();

}

BoolStrExp &BoolStrExp::operator=(const BoolStrExp & other)
{
  BoolStrExp tmp(other);
  swap(tmp);
  return *this;
}

void BoolStrExp::swap(BoolStrExp & other)
{
  std::swap(strexp_, other.strexp_);

}

BoolStrExp::~BoolStrExp()
{
  delete(strexp_);

}

void BoolStrExp::accept(Visitor *v)
{
  v->visitBoolStrExp(this);
}

BoolStrExp *BoolStrExp::clone() const
{
  return new BoolStrExp(*this);
}



/********************   StartsWith    ********************/
StartsWith::StartsWith(ListName *p1, Str p2)
{
  listname_ = p1;
  str_ = p2;

}

StartsWith::StartsWith(const StartsWith & other)
{
  listname_ = other.listname_->clone();
  str_ = other.str_;

}

StartsWith &StartsWith::operator=(const StartsWith & other)
{
  StartsWith tmp(other);
  swap(tmp);
  return *this;
}

void StartsWith::swap(StartsWith & other)
{
  std::swap(listname_, other.listname_);
  std::swap(str_, other.str_);

}

StartsWith::~StartsWith()
{
  delete(listname_);

}

void StartsWith::accept(Visitor *v)
{
  v->visitStartsWith(this);
}

StartsWith *StartsWith::clone() const
{
  return new StartsWith(*this);
}



/********************   EndsWith    ********************/
EndsWith::EndsWith(ListName *p1, Str p2)
{
  listname_ = p1;
  str_ = p2;

}

EndsWith::EndsWith(const EndsWith & other)
{
  listname_ = other.listname_->clone();
  str_ = other.str_;

}

EndsWith &EndsWith::operator=(const EndsWith & other)
{
  EndsWith tmp(other);
  swap(tmp);
  return *this;
}

void EndsWith::swap(EndsWith & other)
{
  std::swap(listname_, other.listname_);
  std::swap(str_, other.str_);

}

EndsWith::~EndsWith()
{
  delete(listname_);

}

void EndsWith::accept(Visitor *v)
{
  v->visitEndsWith(this);
}

EndsWith *EndsWith::clone() const
{
  return new EndsWith(*this);
}



/********************   CompExpAA    ********************/
CompExpAA::CompExpAA(Exp *p1, CompOp p2, Exp *p3)
{
  exp_1 = p1;
  compop_ = p2;
  exp_2 = p3;

}

CompExpAA::CompExpAA(const CompExpAA & other)
{
  exp_1 = other.exp_1->clone();
  compop_ = other.compop_;
  exp_2 = other.exp_2->clone();

}

CompExpAA &CompExpAA::operator=(const CompExpAA & other)
{
  CompExpAA tmp(other);
  swap(tmp);
  return *this;
}

void CompExpAA::swap(CompExpAA & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(compop_, other.compop_);
  std::swap(exp_2, other.exp_2);

}

CompExpAA::~CompExpAA()
{
  delete(exp_1);
  delete(exp_2);

}

void CompExpAA::accept(Visitor *v)
{
  v->visitCompExpAA(this);
}

CompExpAA *CompExpAA::clone() const
{
  return new CompExpAA(*this);
}



/********************   CompExpSC    ********************/
CompExpSC::CompExpSC(Str p1, CompOp p2, Exp *p3)
{
  str_ = p1;
  compop_ = p2;
  exp_ = p3;

}

CompExpSC::CompExpSC(const CompExpSC & other)
{
  str_ = other.str_;
  compop_ = other.compop_;
  exp_ = other.exp_->clone();

}

CompExpSC &CompExpSC::operator=(const CompExpSC & other)
{
  CompExpSC tmp(other);
  swap(tmp);
  return *this;
}

void CompExpSC::swap(CompExpSC & other)
{
  std::swap(str_, other.str_);
  std::swap(compop_, other.compop_);
  std::swap(exp_, other.exp_);

}

CompExpSC::~CompExpSC()
{
  delete(exp_);

}

void CompExpSC::accept(Visitor *v)
{
  v->visitCompExpSC(this);
}

CompExpSC *CompExpSC::clone() const
{
  return new CompExpSC(*this);
}



/********************   CompExpCS    ********************/
CompExpCS::CompExpCS(Exp *p1, CompOp p2, Str p3)
{
  exp_ = p1;
  compop_ = p2;
  str_ = p3;

}

CompExpCS::CompExpCS(const CompExpCS & other)
{
  exp_ = other.exp_->clone();
  compop_ = other.compop_;
  str_ = other.str_;

}

CompExpCS &CompExpCS::operator=(const CompExpCS & other)
{
  CompExpCS tmp(other);
  swap(tmp);
  return *this;
}

void CompExpCS::swap(CompExpCS & other)
{
  std::swap(exp_, other.exp_);
  std::swap(compop_, other.compop_);
  std::swap(str_, other.str_);

}

CompExpCS::~CompExpCS()
{
  delete(exp_);

}

void CompExpCS::accept(Visitor *v)
{
  v->visitCompExpCS(this);
}

CompExpCS *CompExpCS::clone() const
{
  return new CompExpCS(*this);
}



/********************   CompExpBA    ********************/
CompExpBA::CompExpBA(BoolConst p1, CompOp p2, Exp *p3)
{
  boolconst_ = p1;
  compop_ = p2;
  exp_ = p3;

}

CompExpBA::CompExpBA(const CompExpBA & other)
{
  boolconst_ = other.boolconst_;
  compop_ = other.compop_;
  exp_ = other.exp_->clone();

}

CompExpBA &CompExpBA::operator=(const CompExpBA & other)
{
  CompExpBA tmp(other);
  swap(tmp);
  return *this;
}

void CompExpBA::swap(CompExpBA & other)
{
  std::swap(boolconst_, other.boolconst_);
  std::swap(compop_, other.compop_);
  std::swap(exp_, other.exp_);

}

CompExpBA::~CompExpBA()
{
  delete(exp_);

}

void CompExpBA::accept(Visitor *v)
{
  v->visitCompExpBA(this);
}

CompExpBA *CompExpBA::clone() const
{
  return new CompExpBA(*this);
}



/********************   CompExpAB    ********************/
CompExpAB::CompExpAB(Exp *p1, CompOp p2, BoolConst p3)
{
  exp_ = p1;
  compop_ = p2;
  boolconst_ = p3;

}

CompExpAB::CompExpAB(const CompExpAB & other)
{
  exp_ = other.exp_->clone();
  compop_ = other.compop_;
  boolconst_ = other.boolconst_;

}

CompExpAB &CompExpAB::operator=(const CompExpAB & other)
{
  CompExpAB tmp(other);
  swap(tmp);
  return *this;
}

void CompExpAB::swap(CompExpAB & other)
{
  std::swap(exp_, other.exp_);
  std::swap(compop_, other.compop_);
  std::swap(boolconst_, other.boolconst_);

}

CompExpAB::~CompExpAB()
{
  delete(exp_);

}

void CompExpAB::accept(Visitor *v)
{
  v->visitCompExpAB(this);
}

CompExpAB *CompExpAB::clone() const
{
  return new CompExpAB(*this);
}



/********************   ExpSum    ********************/
ExpSum::ExpSum(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

ExpSum::ExpSum(const ExpSum & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

ExpSum &ExpSum::operator=(const ExpSum & other)
{
  ExpSum tmp(other);
  swap(tmp);
  return *this;
}

void ExpSum::swap(ExpSum & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

ExpSum::~ExpSum()
{
  delete(exp_1);
  delete(exp_2);

}

void ExpSum::accept(Visitor *v)
{
  v->visitExpSum(this);
}

ExpSum *ExpSum::clone() const
{
  return new ExpSum(*this);
}



/********************   ExpSub    ********************/
ExpSub::ExpSub(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

ExpSub::ExpSub(const ExpSub & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

ExpSub &ExpSub::operator=(const ExpSub & other)
{
  ExpSub tmp(other);
  swap(tmp);
  return *this;
}

void ExpSub::swap(ExpSub & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

ExpSub::~ExpSub()
{
  delete(exp_1);
  delete(exp_2);

}

void ExpSub::accept(Visitor *v)
{
  v->visitExpSub(this);
}

ExpSub *ExpSub::clone() const
{
  return new ExpSub(*this);
}



/********************   ExpMul    ********************/
ExpMul::ExpMul(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

ExpMul::ExpMul(const ExpMul & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

ExpMul &ExpMul::operator=(const ExpMul & other)
{
  ExpMul tmp(other);
  swap(tmp);
  return *this;
}

void ExpMul::swap(ExpMul & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

ExpMul::~ExpMul()
{
  delete(exp_1);
  delete(exp_2);

}

void ExpMul::accept(Visitor *v)
{
  v->visitExpMul(this);
}

ExpMul *ExpMul::clone() const
{
  return new ExpMul(*this);
}



/********************   ExpDiv    ********************/
ExpDiv::ExpDiv(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

ExpDiv::ExpDiv(const ExpDiv & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

ExpDiv &ExpDiv::operator=(const ExpDiv & other)
{
  ExpDiv tmp(other);
  swap(tmp);
  return *this;
}

void ExpDiv::swap(ExpDiv & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

ExpDiv::~ExpDiv()
{
  delete(exp_1);
  delete(exp_2);

}

void ExpDiv::accept(Visitor *v)
{
  v->visitExpDiv(this);
}

ExpDiv *ExpDiv::clone() const
{
  return new ExpDiv(*this);
}



/********************   ExpConst    ********************/
ExpConst::ExpConst(NumConst *p1)
{
  numconst_ = p1;

}

ExpConst::ExpConst(const ExpConst & other)
{
  numconst_ = other.numconst_->clone();

}

ExpConst &ExpConst::operator=(const ExpConst & other)
{
  ExpConst tmp(other);
  swap(tmp);
  return *this;
}

void ExpConst::swap(ExpConst & other)
{
  std::swap(numconst_, other.numconst_);

}

ExpConst::~ExpConst()
{
  delete(numconst_);

}

void ExpConst::accept(Visitor *v)
{
  v->visitExpConst(this);
}

ExpConst *ExpConst::clone() const
{
  return new ExpConst(*this);
}



/********************   ExpName    ********************/
ExpName::ExpName(ListName *p1)
{
  listname_ = p1;

}

ExpName::ExpName(const ExpName & other)
{
  listname_ = other.listname_->clone();

}

ExpName &ExpName::operator=(const ExpName & other)
{
  ExpName tmp(other);
  swap(tmp);
  return *this;
}

void ExpName::swap(ExpName & other)
{
  std::swap(listname_, other.listname_);

}

ExpName::~ExpName()
{
  delete(listname_);

}

void ExpName::accept(Visitor *v)
{
  v->visitExpName(this);
}

ExpName *ExpName::clone() const
{
  return new ExpName(*this);
}



/********************   ConstFloat    ********************/
ConstFloat::ConstFloat(Double p1)
{
  double_ = p1;

}

ConstFloat::ConstFloat(const ConstFloat & other)
{
  double_ = other.double_;

}

ConstFloat &ConstFloat::operator=(const ConstFloat & other)
{
  ConstFloat tmp(other);
  swap(tmp);
  return *this;
}

void ConstFloat::swap(ConstFloat & other)
{
  std::swap(double_, other.double_);

}

ConstFloat::~ConstFloat()
{

}

void ConstFloat::accept(Visitor *v)
{
  v->visitConstFloat(this);
}

ConstFloat *ConstFloat::clone() const
{
  return new ConstFloat(*this);
}



/********************   ConstInt    ********************/
ConstInt::ConstInt(Integer p1)
{
  integer_ = p1;

}

ConstInt::ConstInt(const ConstInt & other)
{
  integer_ = other.integer_;

}

ConstInt &ConstInt::operator=(const ConstInt & other)
{
  ConstInt tmp(other);
  swap(tmp);
  return *this;
}

void ConstInt::swap(ConstInt & other)
{
  std::swap(integer_, other.integer_);

}

ConstInt::~ConstInt()
{

}

void ConstInt::accept(Visitor *v)
{
  v->visitConstInt(this);
}

ConstInt *ConstInt::clone() const
{
  return new ConstInt(*this);
}



/********************   Keyword    ********************/
Keyword::Keyword(Ident p1)
{
  ident_ = p1;

}

Keyword::Keyword(const Keyword & other)
{
  ident_ = other.ident_;

}

Keyword &Keyword::operator=(const Keyword & other)
{
  Keyword tmp(other);
  swap(tmp);
  return *this;
}

void Keyword::swap(Keyword & other)
{
  std::swap(ident_, other.ident_);

}

Keyword::~Keyword()
{

}

void Keyword::accept(Visitor *v)
{
  v->visitKeyword(this);
}

Keyword *Keyword::clone() const
{
  return new Keyword(*this);
}




/********************   ListName    ********************/

void ListName::accept(Visitor *v)
{
  v->visitListName(this);
}


ListName *ListName::clone() const
{
  return new ListName(*this);
}




