FIND_LIBRARY(ODB_PGSQL_LIBRARY odb-mysql HINT ${ODB_PGSQL_LIBRARY_DIR_HINT})

# handle the QUIETLY and REQUIRED arguments and set ODB_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ODB_PGSQL  DEFAULT_MSG ODB_MYSQL_LIBRARY )

IF(ODB_PGSQL_FOUND)
  SET(ODB_PGSQL_LIBRARIES ${ODB_MYSQL_LIBRARY})
ENDIF()

MARK_AS_ADVANCED(ODB_PGSQL_LIBRARIES)
