if (NOT $ENV{LIBRARY_PATH}  STREQUAL "")
   string (REPLACE ":" ";" LIB_PATHS $ENV{LIBRARY_PATH})
endif ()


FIND_LIBRARY(ODB_BOOST_LIBRARY odb-boost HINTS ${LIB_PATHS})

# handle the QUIETLY and REQUIRED arguments and set ODB_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ODB_BOOST  DEFAULT_MSG ODB_BOOST_LIBRARY )

IF(ODB_BOOST_FOUND)
  SET(ODB_BOOST_LIBRARIES ${ODB_BOOST_LIBRARY})
ENDIF()

MARK_AS_ADVANCED(ODB_BOOST_LIBRARIES ODB_BOOST_LIBRARY)
