FIND_LIBRARY(ODB_MYSQL_LIBRARY odb-mysql HINT ${ODB_MYSQL_LIBRARY_DIR_HINT})

# handle the QUIETLY and REQUIRED arguments and set ODB_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ODB_MYSQL  DEFAULT_MSG ODB_MYSQL_LIBRARY )

IF(ODB_MYSQL_FOUND)
  SET(ODB_MYSQL_LIBRARIES ${ODB_MYSQL_LIBRARY})
ENDIF()

MARK_AS_ADVANCED(ODB_MYSQL_LIBRARIES ODB_MYSQL_LIBRARY)
